FROM envoyproxy/envoy-alpine-dev:latest

RUN apk update && apk add py3-pip bash curl redis
RUN pip3 install -q Flask==0.11.1 requests==2.18.4 redis pyyaml
RUN mkdir /code
ADD ./front-envoy.yaml /code
ADD ./service.py /code
ADD ./set-redis-keys.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/start_service.sh"]
